using System.Collections.Generic;
using System.Linq;
using System.Text;
using CoffeeBeanery.GraphQL.Core.Mapping.Generators.Model;

namespace CoffeeBeanery.GraphQL.Core.Mapping.Generators.Emit
{
    internal static class NodeTreeEmitter
    {
        public static string EmitRegisterOverride(
            MappingClassInfo info,
            NavigationResolutionResult navResult)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using CoffeeBeanery.GraphQL.Core.GraphQL;");
            sb.AppendLine("using CoffeeBeanery.GraphQL.Core.Mapping;");
            sb.AppendLine("using CoffeeBeanery.GraphQL.Core.Sql;");
            sb.AppendLine();

            if (!string.IsNullOrWhiteSpace(info.Namespace))
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"public sealed partial class {info.ClassName}");
            sb.AppendLine("{");

            sb.AppendLine("    public override void Register()");
            sb.AppendLine("    {");

            // --------------------------------------------------
            // IMPORTANT: alias MUST come from runtime base class
            // --------------------------------------------------
            sb.AppendLine("        var alias = this.Alias;");
            sb.AppendLine("        var modelName = this.ModelName;");
            sb.AppendLine();

            EmitModelToEntityKeys(sb, info);
            EmitEntityChildren(sb, info, navResult);
            EmitFieldMapsList(sb, info);
            EmitPerFieldNodes(sb, info);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            if (!string.IsNullOrWhiteSpace(info.Namespace))
                sb.AppendLine("}");

            return sb.ToString();
        }

        // ------------------------------------------------------------
        // MODEL → ENTITY KEYS
        // ------------------------------------------------------------
        private static void EmitModelToEntityKeys(StringBuilder sb, MappingClassInfo info)
        {
            sb.AppendLine("        var modelToEntityKeys = new List<EntityKey>();");

            foreach (var key in info.ModelToEntity)
            {
                var aliasExpr = !string.IsNullOrWhiteSpace(key.AliasProperty)
                    ? $"\"{key.AliasProperty}\""
                    : AliasFor(info, key.EntityType.Name, targetIsRoot: false);

                sb.AppendLine("        modelToEntityKeys.Add(new EntityKey");
                sb.AppendLine("        {");
                sb.AppendLine($"            From = \"{info.ModelType.Name}\",");
                sb.AppendLine("            AliasFrom = alias,");
                sb.AppendLine($"            FromColumn = \"{key.FromColumn}\",");
                sb.AppendLine($"            To = \"{key.To}\",");
                sb.AppendLine($"            AliasTo = {aliasExpr},");
                sb.AppendLine($"            ToColumn = \"{key.ToColumn}\",");
                sb.AppendLine($"            EntityType = typeof({Fqn(key.EntityType)}),");
                sb.AppendLine($"            AliasProperty = {StringOrNull(key.AliasProperty)}");
                sb.AppendLine("        });");
            }

            sb.AppendLine();
        }

        // ------------------------------------------------------------
        // ENTITY CHILDREN (NAVIGATION)
        // ------------------------------------------------------------
        private static void EmitEntityChildren(
            StringBuilder sb,
            MappingClassInfo info,
            NavigationResolutionResult navResult)
        {
            sb.AppendLine("        var entityChildren = new List<EntityKey>();");
            sb.AppendLine("        var entityChildrenRelated = new List<EntityKey>();");
            sb.AppendLine();

            if (!info.IsEntity)
                return;

            foreach (var nav in navResult.Navigations)
            {
                var targetList = nav.IsCollection
                    ? "entityChildren"
                    : "entityChildrenRelated";

                var aliasExpr = AliasFor(info, nav.NavigationName, nav.TargetIsRoot);

                sb.AppendLine($"        {targetList}.Add(new EntityKey");
                sb.AppendLine("        {");
                sb.AppendLine($"            From = \"{info.ModelType.Name}\",");
                sb.AppendLine("            AliasFrom = alias,");
                sb.AppendLine($"            FromColumn = \"{nav.ForeignKeyProperty}\",");
                sb.AppendLine($"            To = \"{nav.RelatedEntityType.Name}\",");
                sb.AppendLine($"            AliasTo = {aliasExpr},");
                sb.AppendLine($"            ToColumn = \"{nav.PrincipalKeyProperty}\",");
                sb.AppendLine($"            EntityType = typeof({Fqn(nav.RelatedEntityType)})");
                sb.AppendLine("        });");
            }

            sb.AppendLine();
        }

        // ------------------------------------------------------------
        // FIELD MAPS
        // ------------------------------------------------------------
        private static void EmitFieldMapsList(StringBuilder sb, MappingClassInfo info)
        {
            sb.AppendLine("        var fieldMaps = new List<FieldMap>();");

            foreach (var fm in info.FieldMaps)
            {
                sb.AppendLine("        fieldMaps.Add(new FieldMap");
                sb.AppendLine("        {");
                sb.AppendLine($"            SourceModel = \"{info.ModelType.Name}\",");
                sb.AppendLine($"            SourceName = \"{fm.SourceName}\",");
                sb.AppendLine($"            DestinationEntity = \"{fm.DestinationEntity}\",");
                sb.AppendLine($"            DestinationName = \"{fm.DestinationName}\",");
                sb.AppendLine($"            SourceAlias = {StringOrAlias(info, fm.SourceAlias)},");
                sb.AppendLine($"            DestinationAlias = {StringOrAlias(info, fm.DestinationAlias)},");
                sb.AppendLine($"            FromEnum = {EmitDict(fm.FromEnum)},");
                sb.AppendLine($"            ToEnum = {EmitDict(fm.ToEnum)}");
                sb.AppendLine("        });");
            }

            sb.AppendLine();
        }

        // ------------------------------------------------------------
        // PER FIELD NODES (SQL + GRAPH INDEX)
        // ------------------------------------------------------------
        private static void EmitPerFieldNodes(StringBuilder sb, MappingClassInfo info)
        {
            sb.AppendLine("        foreach (var field in fieldMaps)");
            sb.AppendLine("        {");

            sb.AppendLine("            var relationshipKey = $\"{alias}~{modelName}~{field.SourceName}\";");
            sb.AppendLine();

            sb.AppendLine("            var modelNode = new ModelNode");
            sb.AppendLine("            {");
            sb.AppendLine("                Id = this.Id.ToString(),");
            sb.AppendLine($"                Prefix = \"{info.Prefix}\",");
            sb.AppendLine($"                Table = \"{info.EntityType?.Name}\",");
            sb.AppendLine("                Column = field.DestinationName,");
            sb.AppendLine("                SourceColumn = field.SourceName,");
            sb.AppendLine("                RelationshipKey = relationshipKey");
            sb.AppendLine("            };");

            sb.AppendLine();
            sb.AppendLine("            NodeRegistry.RegisterNode(");
            sb.AppendLine("                relationshipKey,");
            sb.AppendLine("                relationshipKey,");
            sb.AppendLine("                modelNode,");
            sb.AppendLine($"                typeof({Fqn(info.ModelType)}),");
            sb.AppendLine($"                {(info.EntityType is null ? $"typeof({Fqn(info.ModelType)})" : $"typeof({Fqn(info.EntityType)})")},");
            sb.AppendLine($"                {Bool(info.IsEntity)});");
            sb.AppendLine();

            sb.AppendLine("        }");
        }

        // ------------------------------------------------------------
        // HELPERS
        // ------------------------------------------------------------

        private static string AliasFor(MappingClassInfo info, string seed, bool targetIsRoot)
        {
            if (targetIsRoot)
                return $"\"{seed}\"";

            return string.IsNullOrWhiteSpace(info.Prefix)
                ? $"\"{seed}\""
                : $"\"{info.Prefix}{seed}\"";
        }

        private static string StringOrAlias(MappingClassInfo info, string? value)
        {
            if (string.IsNullOrWhiteSpace(value))
                return "null";

            if (value == "{alias}" || value == info.Alias)
                return "alias";

            return $"\"{value}\"";
        }

        private static string StringOrNull(string? value)
            => value is null ? "null" : $"\"{value}\"";

        private static string EmitDict(Dictionary<string, int>? dict)
        {
            if (dict is null || dict.Count == 0)
                return "null";

            return "new Dictionary<string,int> { " +
                   string.Join(", ", dict.Select(kv => $"[\"{kv.Key}\"] = {kv.Value}")) +
                   " }";
        }

        private static string Bool(bool b) => b ? "true" : "false";

        private static string Fqn(Microsoft.CodeAnalysis.INamedTypeSymbol symbol)
            => symbol.ToDisplayString(
                Microsoft.CodeAnalysis.SymbolDisplayFormat.FullyQualifiedFormat)
                .TrimStart(':');
    }
}